# runtime = { FetchVersion = "latest" }
runtime = { RepoPath = "../../../kinode" }
persist_home = false
runtime_build_release = false


# [[tests]]
# dependency_package_paths = ["javascript/no-ui/chat"]
# setup_packages = [
#     { path = "javascript/no-ui/chat", run = true }
# ]
# setup_scripts = []
# test_package_paths = ["javascript/no-ui/chat/test/chat-test"]
# test_scripts = []
# timeout_secs = 5
# fakechain_router = 8545
#
# [[tests.nodes]]
# port = 8080
# home = "home/first"
# fake_node_name = "first.dev"
# runtime_verbosity = 2
#
# [[tests.nodes]]
# port = 8081
# home = "home/second"
# fake_node_name = "second.dev"
# runtime_verbosity = 2
#
#
# [[tests]]
# dependency_package_paths = []
# setup_packages = [
#     { path = "javascript/no-ui/echo", run = true }
# ]
# setup_scripts = []
# test_package_paths = ["javascript/no-ui/echo/test/echo-test"]
# test_scripts = []
# timeout_secs = 5
# fakechain_router = 8545
#
# [[tests.nodes]]
# port = 8080
# home = "home/first"
# fake_node_name = "first.dev"
# runtime_verbosity = 2
#
#
# [[tests]]
# dependency_package_paths = ["javascript/no-ui/fibonacci"]
# setup_packages = [
#     { path = "javascript/no-ui/fibonacci", run = true }
# ]
# setup_scripts = []
# test_package_paths = ["javascript/no-ui/fibonacci/test/fibonacci-test"]
# test_scripts = []
# timeout_secs = 5
# fakechain_router = 8545
#
# [[tests.nodes]]
# port = 8080
# home = "home/first"
# fake_node_name = "first.dev"
# runtime_verbosity = 2
#
#
# [[tests]]
# dependency_package_paths = ["python/no-ui/chat"]
# setup_packages = [
#     { path = "python/no-ui/chat", run = true }
# ]
# setup_scripts = []
# test_package_paths = ["python/no-ui/chat/test/chat-test"]
# test_scripts = []
# timeout_secs = 5
# fakechain_router = 8545
#
# [[tests.nodes]]
# port = 8080
# home = "home/first"
# fake_node_name = "first.dev"
# runtime_verbosity = 2
#
# [[tests.nodes]]
# port = 8081
# home = "home/second"
# fake_node_name = "second.dev"
# runtime_verbosity = 2
#
#
# [[tests]]
# dependency_package_paths = []
# setup_packages = [
#     { path = "python/no-ui/echo", run = true }
# ]
# setup_scripts = []
# test_package_paths = ["python/no-ui/echo/test/echo-test"]
# test_scripts = []
# timeout_secs = 5
# fakechain_router = 8545
#
# [[tests.nodes]]
# port = 8080
# home = "home/first"
# fake_node_name = "first.dev"
# runtime_verbosity = 2
#
#
# [[tests]]
# dependency_package_paths = ["python/no-ui/fibonacci"]
# setup_packages = [
#     { path = "python/no-ui/fibonacci", run = true }
# ]
# setup_scripts = []
# test_package_paths = ["python/no-ui/fibonacci/test/fibonacci-test"]
# test_scripts = []
# timeout_secs = 5
# fakechain_router = 8545
#
# [[tests.nodes]]
# port = 8080
# home = "home/first"
# fake_node_name = "first.dev"
# runtime_verbosity = 2


[[tests]]
dependency_package_paths = ["rust/no-ui/chat"]
setup_packages = [
    { path = "rust/no-ui/chat", run = true }
]
setup_scripts = []
test_package_paths = ["rust/no-ui/chat/test/chat-test"]
test_scripts = []
timeout_secs = 5
fakechain_router = 8545

[[tests.nodes]]
port = 8080
home = "home/first"
fake_node_name = "first.dev"
runtime_verbosity = 2

[[tests.nodes]]
port = 8081
home = "home/second"
fake_node_name = "second.dev"
runtime_verbosity = 2


[[tests]]
dependency_package_paths = []
setup_packages = [
    { path = "rust/no-ui/echo", run = true }
]
setup_scripts = []
test_package_paths = ["rust/no-ui/echo/test/echo-test"]
test_scripts = []
timeout_secs = 5
fakechain_router = 8545

[[tests.nodes]]
port = 8080
home = "home/first"
fake_node_name = "first.dev"
runtime_verbosity = 2


[[tests]]
dependency_package_paths = ["rust/no-ui/fibonacci"]
setup_packages = [
    { path = "rust/no-ui/fibonacci", run = true }
]
setup_scripts = []
test_package_paths = ["rust/no-ui/fibonacci/test/fibonacci-test"]
test_scripts = []
timeout_secs = 5
fakechain_router = 8545

[[tests.nodes]]
port = 8080
home = "home/first"
fake_node_name = "first.dev"
runtime_verbosity = 2


# [[tests]]
# setup_packages = [
#     { path = "rust/no-ui/file-transfer", run = true }
# ]
# setup_scripts = []
# test_package_paths = ["rust/no-ui/file-transfer/test/file-transfer-test"]
# test_scripts = []
# timeout_secs = 5
# fakechain_router = 8545
#
# [[tests.nodes]]
# port = 8080
# home = "home/first"
# fake_node_name = "first.dev"
# runtime_verbosity = 2
#
# [[tests.nodes]]
# port = 8081
# home = "home/second"
# fake_node_name = "second.dev"
# runtime_verbosity = 2
